Export generateCommand function - we may want to modify before writing
withfig/autocomplete-tools pull request #26
Opened 2021-12-09 03:52 UTC by slatlasdev

**What kind of change does this PR introduce? (Bug fix, feature, docs update, ...)**

Feature 

**What is the current behavior? (You can also link to an open issue here)**

You cannot edit the spec before it is written to file.

**What is the new behavior (if this is a feature change)?**

This allows package consumers to call the `generateCommand` function directly, as they may want to edit the output before it is written to a file.

**Additional info:**

2021-12-09 15:36 UTC, fedeci requested changes
Could you bridge this export to the main `index.ts` too, please?
I thing in the future we may provide a class so that is easier to override methods.

2021-12-10 00:11 UTC, slatlasdev commented
@fedeci Sorry, could you clarify which `index.ts` file it would be included in? I assume not https://github.com/withfig/autocomplete-tools/blob/main/packages/autocomplete-tools/index.ts as this seems to be just for CLI usage of this tool, whereas the change I made is more for programmatic usage.

2021-12-10 00:17 UTC, fedeci commented
Damn, we do not have a index.ts at the root of the commander package, sorry for the bad review, LGTM!

2021-12-10 00:17 UTC, fedeci approved these changes

2021-12-10 00:17 UTC, merged